version: '3'
services:
  db:
    image: mongo:4.2.0-rc1-bionic
    container_name: MongoMevn
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - appnet
  mevn:
    build: .
    restart: always
    ports:
      - '49160:3000'
    depends_on:
      - 'db'
    networks:
      - appnet
networks:
  appnet:
    driver: bridge

# Run docker-compose up db (Only development environment) to run only a database
